service: todo-service

frameworkVersion: '3'

provider:
  name: azure
  region: West US 2
  runtime: nodejs14
  os: linux
  # prefix: "sample"  # prefix of generated resource name
  # subscriptionId: A356AC8C-E310-44F4-BF85-C7F29044AF99
  # stage: dev
  # type: premium  # premium azure functions

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions
  - serverless-dotenv-plugin

# you can add packaging information here
package:
  patterns:
    # - '!exclude-me.js'
    # - '!exclude-me-dir/**'
    - '!local.settings.json'
    - '!.vscode/**'
    # - include-me.js
    # - include-me-dir/**

functions:
  addTodo:
    handler: src/handler.addTodo
    events:
      - http: true
        methods:
          - POST
        route: todos/

  getTodos:
    handler: src/handler.getTodos
    events:
      - http: true
        methods:
          - GET
        route: todos/
  
  updateTodo:
    handler: src/handler.updateTodo
    events:
      - http: true
        methods:
          - PUT
        route: todos/{todoId}

  deleteTodo:
    handler: src/handler.deleteTodo
    events:
      - http: true
        methods:
          - DELETE
        route: todos/{todoId}

  getTodo:
    handler: src/handler.getTodo
    events:
      - http: true
        methods:
          - GET
        route: todos/{todoId}